In [22]:
import pandas as pd 
import numpy as np
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report
from process import *
from datetime import timedelta
from sklearn.metrics import confusion_matrix


In [23]:
df_filt = pd.read_csv('df_filt.csv')
df_test = pd.read_csv('df_test.csv')   
df_filt['Timestamp'] = pd.to_datetime(df_filt['Timestamp'])
df_test['Timestamp'] = pd.to_datetime(df_test['Timestamp'])

In [24]:
features_filt = features_tsfel(df_filt, w_size=100, w_overlap=0, t_time=timedelta(microseconds=10000), n_jobs=6)

In [25]:
print(features_filt.columns)

Index(['Back.Acc.X_Absolute energy', 'Back.Acc.X_Area under the curve',
       'Back.Acc.X_Autocorrelation', 'Back.Acc.X_Average power',
       'Back.Acc.X_Centroid', 'Back.Acc.X_ECDF Percentile Count_0',
       'Back.Acc.X_ECDF Percentile Count_1', 'Back.Acc.X_ECDF Percentile_0',
       'Back.Acc.X_ECDF Percentile_1', 'Back.Acc.X_ECDF_0',
       ...
       'Neck.Mag.Z_Wavelet variance_25.0Hz',
       'Neck.Mag.Z_Wavelet variance_3.12Hz',
       'Neck.Mag.Z_Wavelet variance_3.57Hz',
       'Neck.Mag.Z_Wavelet variance_4.17Hz',
       'Neck.Mag.Z_Wavelet variance_5.0Hz',
       'Neck.Mag.Z_Wavelet variance_6.25Hz',
       'Neck.Mag.Z_Wavelet variance_8.33Hz', 'Neck.Mag.Z_Zero crossing rate',
       'Subject', 'Position'],
      dtype='object', length=4214)


In [26]:
features_test = features_tsfel(df_test, w_size=100, w_overlap=0, t_time=timedelta(microseconds=10000), n_jobs=6)

In [27]:
features_filt_50 = features_tsfel(df_filt, w_size=100, w_overlap=0.5, t_time=timedelta(microseconds=5000), n_jobs=6)

In [28]:
features_test_50 = features_tsfel(df_test, w_size=100, w_overlap=0.5, t_time=timedelta(microseconds=5000), n_jobs=6)

In [29]:
lista_colunas = features_filt.columns.tolist()
print(lista_colunas)

['Back.Acc.X_Absolute energy', 'Back.Acc.X_Area under the curve', 'Back.Acc.X_Autocorrelation', 'Back.Acc.X_Average power', 'Back.Acc.X_Centroid', 'Back.Acc.X_ECDF Percentile Count_0', 'Back.Acc.X_ECDF Percentile Count_1', 'Back.Acc.X_ECDF Percentile_0', 'Back.Acc.X_ECDF Percentile_1', 'Back.Acc.X_ECDF_0', 'Back.Acc.X_ECDF_1', 'Back.Acc.X_ECDF_2', 'Back.Acc.X_ECDF_3', 'Back.Acc.X_ECDF_4', 'Back.Acc.X_ECDF_5', 'Back.Acc.X_ECDF_6', 'Back.Acc.X_ECDF_7', 'Back.Acc.X_ECDF_8', 'Back.Acc.X_ECDF_9', 'Back.Acc.X_Entropy', 'Back.Acc.X_Fundamental frequency', 'Back.Acc.X_Histogram mode', 'Back.Acc.X_Human range energy', 'Back.Acc.X_Interquartile range', 'Back.Acc.X_Kurtosis', 'Back.Acc.X_LPCC_0', 'Back.Acc.X_LPCC_1', 'Back.Acc.X_LPCC_10', 'Back.Acc.X_LPCC_11', 'Back.Acc.X_LPCC_2', 'Back.Acc.X_LPCC_3', 'Back.Acc.X_LPCC_4', 'Back.Acc.X_LPCC_5', 'Back.Acc.X_LPCC_6', 'Back.Acc.X_LPCC_7', 'Back.Acc.X_LPCC_8', 'Back.Acc.X_LPCC_9', 'Back.Acc.X_MFCC_0', 'Back.Acc.X_MFCC_1', 'Back.Acc.X_MFCC_10', 'Back.Ac

In [31]:
columns_mean_filt = df_filt.columns[df_filt.columns.str.contains(r'\.(X|Y|Z)_Mean$', regex=True)]
columns_mean_test = df_test.columns[df_test.columns.str.contains(r'\.(X|Y|Z)_Mean$', regex=True)]

dados_mean_filt = df_filt[columns_mean_filt]
dados_mean_test = df_test[columns_mean_test]

x_treino = dados_mean_filt
y_treino = df_filt["Position"]
x_teste = dados_mean_test
y_teste = df_test["Position"]

rf = RandomForestClassifier(
    n_estimators=300,        # número de árvores
    max_depth=12,          # deixe None inicialmente
    min_samples_split=2,
    min_samples_leaf=1,     # padrão bom para classificação
    bootstrap=True,
    n_jobs=6,
    random_state=42
)

rf.fit(x_treino, y_treino)
y_pred = rf.predict(x_teste)

acc = accuracy_score(y_teste, y_pred)
print(f"Acurácia: {acc:.4f}")

print(classification_report(y_teste, y_pred))

cm = confusion_matrix(y_teste, y_pred)
print(cm)

C:\Users\assis\AppData\Local\Temp\ipykernel_14876\1986011192.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  columns_mean_filt = df_filt.columns[df_filt.columns.str.contains(r'\.(X|Y|Z)_Mean$', regex=True)]
C:\Users\assis\AppData\Local\Temp\ipykernel_14876\1986011192.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  columns_mean_test = df_test.columns[df_test.columns.str.contains(r'\.(X|Y|Z)_Mean$', regex=True)]


ValueError: at least one array or dtype is required

In [ ]:
columns_std_filt = df_filt.columns[df_filt.columns.str.contains(r'\.(X|Y|Z)_Standard deviation$', regex=True)]
columns_std_test = df_test.columns[df_test.columns.str.contains(r'\.(X|Y|Z)_Standard deviation$', regex=True)]
dados_std_filt = df_filt[columns_std_filt]
dados_std_test = df_test[columns_std_test]
x_treino_std = dados_std_filt
x_teste_std = dados_std_test
y_treino_std = df_filt["Position"]
y_teste_std = df_test["Position"]

rf = RandomForestClassifier(
    n_estimators=300,        # número de árvores
    max_depth=12,          # deixe None inicialmente
    min_samples_split=2,
    min_samples_leaf=1,     # padrão bom para classificação
    bootstrap=True,
    n_jobs=6,
    random_state=42
)

rf.fit(x_treino_std, y_treino_std)
y_pred_std = rf.predict(x_teste_std)

acc_std = accuracy_score(y_teste_std, y_pred_std)
print(f"Acurácia (std): {acc_std:.4f}")

print(classification_report(y_teste_std, y_pred_std))
cm_std = confusion_matrix(y_teste_std, y_pred_std)
print(cm_std)


C:\Users\assis\AppData\Local\Temp\ipykernel_8376\4091284723.py:1: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  columns_std_filt = df_filt.columns[df_filt.columns.str.contains(r'\.(X|Y|Z)_Standard deviation$', regex=True)]
C:\Users\assis\AppData\Local\Temp\ipykernel_8376\4091284723.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  columns_std_test = df_test.columns[df_test.columns.str.contains(r'\.(X|Y|Z)_Standard deviation$', regex=True)]


Acurácia (std): 0.8578
              precision    recall  f1-score   support

  body shake       0.00      0.00      0.00         4
  lying down       0.00      0.00      0.00         0
     sitting       0.84      0.92      0.88       220
    standing       0.82      0.70      0.75       127
     walking       0.97      0.99      0.98        78

    accuracy                           0.86       429
   macro avg       0.53      0.52      0.52       429
weighted avg       0.85      0.86      0.85       429

[[  0   0   0   2   2]
 [  0   0   0   0   0]
 [  0   1 202  17   0]
 [  0   0  38  89   0]
 [  0   0   0   1  77]]


c:\Users\assis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\assis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\assis\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [ ]:
# # Definindo os hiperparâmetros para Grid Search (3 valores para cada)
# param_grid = {
#     'n_estimators': [100, 200, 300],           # número de árvores
#     'max_depth': [10, 15, 20],                # profundidade máxima
#     'min_samples_leaf': [10, 20, 30]         # mínimo de amostras por folha
# }

# # Criando o modelo base
# rf_base = RandomForestClassifier(
#     n_estimators=300,        # número de árvores
#     max_depth=12,          # deixe None inicialmente
#     min_samples_split=2,
#     min_samples_leaf=1,     # padrão bom para classificação
#     bootstrap=True,
#     n_jobs=6,
#     random_state=42
# )

# # Grid Search com Cross-Validation de 5 folds
# # print("Iniciando Grid Search com 5-fold Cross-Validation...")
# # print(f"Total de combinações: {len(param_grid['n_estimators']) * len(param_grid['max_depth']) * len(param_grid['min_samples_leaf'])}")
# # print("="*60)

# # grid_search = GridSearchCV(
# #     estimator=rf_base,
# #     param_grid=param_grid,
# #     cv=5,                    # 5 folds
# #     scoring='accuracy',
# #     n_jobs=6,
# #     verbose=2,
# #     return_train_score=True
# # )

